# Exported from https://tiplanet.org/pb/ on Mon Nov 13 14:58:31 2023 (CET)

# ----------------------------
# Program Options
# ----------------------------

NAME         ?= CHATAI
ICON         ?= icon.png
DESCRIPTION  ?= ""
COMPRESSED   ?= YES
ARCHIVED     ?= YES

# ----------------------------
# Compile Options
# ----------------------------

CFLAGS   ?= -Oz -W -Wall -Wextra -Wwrite-strings
CXXFLAGS ?= -Oz -W -Wall -Wextra -Wwrite-strings

# ----------------------------

include $(shell cedev-config --makefile)
